[phases.setup]
nixPkgs = ["(php82.withExtensions ({ enabled, all }: enabled ++ [ all.pdo_mysql all.mbstring all.opcache ]))"]

[phases.install]
cmds = []

[phases.build]
cmds = []

[start]
cmd = "php -S 0.0.0.0:$PORT router.php"
